name: flutter_laboratorio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.7.0
  provider: ^6.1.5+1
  audioplayers: ^6.8.1
  sensors_plus: ^7.1.1
  share_plus: ^13.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/Fondo_madera.jpg
    - assets/icons/icon_image.png
    - assets/audio/

  # Declaracion de fuentes personalizadas
  fonts:
    - family: Wildeast
      fonts:
        - asset: assets/fonts/The Wildeast.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon_image.png"
  min_sdk_android: 21

  
